## Loading libraries

In [80]:
import pandas as pd
import numpy as np

### First source

In [81]:
df1=pd.read_csv("datasets/all_poems.csv")

In [82]:
df1.duplicated().sum()

np.int64(0)

In [83]:
df1.columns
df1.drop([ 'poem_link', 'poet_id', 'poet_link','poem_id','poet_cat'],axis=1,inplace=True)

In [84]:
df1

,poem_style,poem_text,poem_title,poet_name
0,فصحى,عيناك غابتا نخيل ساعة السحر او شرفتان راح يناي...,أنشودة المطر,بدر شاكر السياب
1,فصحى,انا لا ازال و في يدي قدحي ياليل اين تفرق الشر...,أقداح و أحلام,بدر شاكر السياب
2,فصحى,علي مقلتيك ارتشفت النجوم وعانقت امالي الايبة ...,هوى واحد !,بدر شاكر السياب
3,فصحى,اساطير من حشرجات الزمان نسيج اليد البالية رواه...,أساطير,بدر شاكر السياب
4,فصحى,والتف حولك ساعداي ومال جيدك في اشتهاء كالزهرة ...,اللقاء الأخير,بدر شاكر السياب
...,...,...,...,...
58016,فصحى,لروح صهيل لا تحويه الاوقات ذنبك انك تمتد علي ا...,الوقت,عز الدين اليوسف
58017,فصحى,اه لو اني ابني الشمس بعيني من طين هواء وسراب م...,الفلاح,عز الدين اليوسف
58018,فصحى,في عينيك يا امي لماذا الدمع منتظم كعقد الءلء ا...,أمّي,عز الدين اليوسف
58019,فصحى,النوم يوقظ طرفي الظامي علي لحن تموج من بعيد ار...,عن اللحن,عز الدين اليوسف
58020,فصحى,السلم الذي نزلت فيه لسماء سلم من الجنان جاء او...,السلم,عز الدين اليوسف

In [85]:
df1['poem_style'].unique()

array(['فصحى', '-', 'عامي'], dtype=object)

In [86]:
df1=df1[df1['poem_style']=='عامي']

In [87]:
df1

,poem_style,poem_text,poem_title,poet_name
2133,عامي,الا واشيب عيني يوم قالوا لي فمان اله وتحقت ان...,ألا واشيب عيني,عبدالله الفيصل
3693,عامي,يا ابناء الارض انتشروا دقت اجراس الميلاد ضموا...,يا أبناء الأرض,طلعت سقيرق
3694,عامي,فرسانا زين الشباب زين الشباب فرسانا نادي الوط...,تسلم إيديكو,طلعت سقيرق
3695,عامي,ارضي يا احلي من الهوي ومن لهفتو سكر المطر لما...,موال: أرضي يا أحلى من الهوى,طلعت سقيرق
3696,عامي,فجرك طلع واله مع زهرك بلادي سيفك حجر واله وما...,الفجر الفلسطيني,طلعت سقيرق
...,...,...,...,...
45336,عامي,انا كخصرك نحيل والدمع راحي تخمينك اني عليل دا...,أَنا كَخصرك نَحيل,عائشة التيمورية
45424,عامي,بتهجر ليه اسير حبك يا روحي ولك اوصاف ترد الرو...,بتهجر ليه أَسير حُبِّك يا روحي,عائشة التيمورية
45426,عامي,انا ما اسلي غرام لو سلوني وروحي في راحات حبك ...,اَنا ما أَسلى غَرام لَو سَلوني,عائشة التيمورية
45484,عامي,سلامة مهجتي م الاه تعا يا قلب نعيها لهو انت ا...,سَلامة مهجَتي م الآه,عائشة التيمورية
50413,عامي,"قالها في اخر حبيبة وهي نفسها التي غني لها ""يام...",الأحلام الكبار,عبدالله عبدالوهاب نعمان

In [88]:
df1

,poem_style,poem_text,poem_title,poet_name
2133,عامي,الا واشيب عيني يوم قالوا لي فمان اله وتحقت ان...,ألا واشيب عيني,عبدالله الفيصل
3693,عامي,يا ابناء الارض انتشروا دقت اجراس الميلاد ضموا...,يا أبناء الأرض,طلعت سقيرق
3694,عامي,فرسانا زين الشباب زين الشباب فرسانا نادي الوط...,تسلم إيديكو,طلعت سقيرق
3695,عامي,ارضي يا احلي من الهوي ومن لهفتو سكر المطر لما...,موال: أرضي يا أحلى من الهوى,طلعت سقيرق
3696,عامي,فجرك طلع واله مع زهرك بلادي سيفك حجر واله وما...,الفجر الفلسطيني,طلعت سقيرق
...,...,...,...,...
45336,عامي,انا كخصرك نحيل والدمع راحي تخمينك اني عليل دا...,أَنا كَخصرك نَحيل,عائشة التيمورية
45424,عامي,بتهجر ليه اسير حبك يا روحي ولك اوصاف ترد الرو...,بتهجر ليه أَسير حُبِّك يا روحي,عائشة التيمورية
45426,عامي,انا ما اسلي غرام لو سلوني وروحي في راحات حبك ...,اَنا ما أَسلى غَرام لَو سَلوني,عائشة التيمورية
45484,عامي,سلامة مهجتي م الاه تعا يا قلب نعيها لهو انت ا...,سَلامة مهجَتي م الآه,عائشة التيمورية
50413,عامي,"قالها في اخر حبيبة وهي نفسها التي غني لها ""يام...",الأحلام الكبار,عبدالله عبدالوهاب نعمان

### Second source

In [89]:
df2=pd.read_csv("datasets/Arabic_poetry_dataset 2.csv")

In [90]:
df2['category'].unique()

array(['الإمارات', 'البحرين', 'الجزائر', 'السعودية', 'السودان', 'العراق',
       'المغرب', 'اليمن', 'تونس', 'سوريا', 'عمان', 'فلسطين', 'لبنان',
       'ليبيا', 'مصر', 'الأردن', 'الكويت', 'قطر', 'موريتانيا',
       'العصر الجاهلي', 'العصر الإسلامي', 'العصر العباسي',
       'العصر الايوبي', 'العصر العثماني', 'عصر المخضرمون', 'العصر الاموي',
       'العصر الأندلسي', 'العصر المملوكي'], dtype=object)

### Third source

In [91]:
df3=pd.read_csv("datasets/Arabic_Poetry_Dataset.csv")

In [92]:
df3

,poet_name,poet_era,poem_tags,poem_title,poem_text,poem_count
0,لقيط بن يعمر الإيادي,العصر الجاهلي,"قصائد هجاء, عموديه, بحر الوافر, قافية الدال (د)",سلام في الصحيفة من لقيط,سَلامٌ في الصَحيفَةِ مِن لَقيطٍ\nإِلى مَن بِال...,عدد الابيات : 4
1,لقيط بن يعمر الإيادي,العصر الجاهلي,"قصائد حزينه, عموديه, بحر البسيط, قافية الألف ...",يا دار عمرة من محتلها الجرعا,يا دارَ عَمرَةَ مِن مُحتَلِّها الجَرَعا\nهاجَت...,عدد الابيات : 60
2,لقيط بن يعمر الإيادي,العصر الجاهلي,"قصائد قصيره, عموديه, بحر الرجز, قافية الألف (ا)",وخاننا خوان في ارتباعنا,وَخانَنا خَوّانٌ في اِرتِباعِنا\nفَاِنفَدَّ لِ...,عدد الابيات : 1
3,زبان بن سيار الفزاري,العصر الجاهلي,"قصائد قصيره, عموديه, بحر الطويل, قافية الألف ...",تنح إليكم يا ابن كوز فإننا,تَنَحَّ إِلَيكُم يا اِبنَ كوزٍ فَإِنَّنا\nوَإِ...,عدد الابيات : 1
4,زبان بن سيار الفزاري,العصر الجاهلي,"قصائد قصيره, عموديه, بحر الطويل, قافية الباء ...",تطارحه الأنساب حتى رددنه,تُطارِحُهُ الأَنسابُ حَتّى رَدَدنَهُ\nإِلى نَس...,عدد الابيات : 1
...,...,...,...,...,...,...
75017,أبو شراعة,العصر العباسي,"قصائد حزينه, عموديه, بحر الخفيف, قافية اللام ...",تلوم جودي لبرمة الطفشيل,تَلومُ جودي لِبُرمَةِ الطَفشيلِ\nوَاِستَهِلّي ...,عدد الابيات : 9
75018,أبو شراعة,العصر العباسي,"قصائد رومنسيه, عموديه, بحر البسيط, قافية اللا...",وردت دار سعيد وهي خالية,وَرَدتُ دارَ سَعيدٍ وَهيَ خالِيَةٌ\nوَكانَ أَب...,عدد الابيات : 4
75019,أبو شراعة,العصر العباسي,"قصائد قصيره, عموديه, بحر الطويل, قافية الياء ...",ألا لا أبالي في العلى ما أصابني,أَلا لا أُبالي في العُلى ما أَصابَني\nوَإِن نَ...,عدد الابيات : 3
75020,أبو شراعة,العصر العباسي,"قصائد عتاب, عموديه, بحر الوافر, قافية الياء (ي)",بني سوار إن رثت ثيابي,بَني سَوّارَ إِن رَثَت ثِيابي\nوَكَلَّ عَنِ ال...,عدد الابيات : 9
75021,أبو شراعة,العصر العباسي,"قصائد عتاب, عموديه, بحر الطويل, قافية النون (ن)",تلوم ابنة البكري حين أؤوبها,تَلومُ اِبنَةُ البِكرِيِّ حينَ أَؤوبُها\nهَزيل...,عدد الابيات : 5

In [93]:
df3['poet_era'].unique()

array(['العصر الجاهلي', 'المخضرمون', 'العصر الاسلامي', 'العصر الاموي',
       'العصر الايوبي', 'العصر العثماني', 'العصر الأندلسي',
       'العصر المملوكي', 'العصر العباسي'], dtype=object)

In [94]:
df3['poet_era'].value_counts()

poet_era
العصر العباسي     26725
العصر المملوكي    13085
العصر الايوبي      8189
العصر العثماني     7545
العصر الاموي       7330
العصر الأندلسي     6171
المخضرمون          3290
العصر الجاهلي      2350
العصر الاسلامي      337
Name: count, dtype: int64

### fourth source

In [95]:
df4=pd.read_csv("datasets/archive (3)/Arabic PCD/Arabic Poem Comprehensive Dataset (APCD).csv")

In [96]:
df4

,العصر,الشاعر,الديوان,القافية,البحر,الشطر الايسر,الشطر الايمن,البيت
0,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَأَن تَجمَعا شَملي وَتَنتَظِرا غَدا,خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا,خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا وَأَن...
1,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَلا سُرعَتي يَوماً بِسابِقَةِ الرَدى,فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ,فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ وَلا سُ...
2,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَتَستَوجِبا مَنّاً عَلَيَّ وَتُحمَدا,وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً,وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً وَتَ...
3,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,تُؤامِرُني سِرّاً لِأَصرِمَ مَرثَدا,لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ,لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ تُؤامِرُ...
4,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَأَفرَعَ في لَومي مِراراً وَأَصعَدا,وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ,وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ وَأَفر...
...,...,...,...,...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,وأحلى قصيدة تَتَغنى,هي أغلى ما أنشأ اللَّه في الدنيا,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,كحلم يغشى الجفون الوسنى,هي أغرودة الأغاريد تنساب,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يتداعى وجداً ويخفق حسنا,هي شلال بهجة وبهاء,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يدك الحدود سجناً فسجنا,هي حلم الهوى ومنطلقي الباقي,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,آه لو أدرك الغرام لجنا,هي حبي العاتي وكل غرامي,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

In [97]:
df4.columns

Index(['العصر', 'الشاعر', 'الديوان', 'القافية', 'البحر', 'الشطر الايسر',
       'الشطر الايمن', 'البيت'],
      dtype='object')

In [98]:
df4['العصر'].value_counts()

العصر
الحديث             778723
العباسي            234494
المملوكي           164780
العثماني           159576
الفاطمي            124129
الأيوبي            112350
المغرب والأندلس    111011
الأموي              63776
المخضرمين           34005
بين الدولتين        24077
قبل الإسلام         21907
الإسلامي             2942
Name: count, dtype: int64

In [99]:
df4=df4[df4['العصر']=='الحديث']

In [100]:
df4

,العصر,الشاعر,الديوان,القافية,البحر,الشطر الايسر,الشطر الايمن,البيت
198186,الحديث,أحمد شوقي,الديوان الرئيسي,ء,الخفيف,وَحَداها بِمَن تُقِلُّ الرَجاءُ,هَمَّتِ الفُلكُ وَاِحتَواها الماءُ,هَمَّتِ الفُلكُ وَاِحتَواها الماءُ وَحَداها...
198187,الحديث,أحمد شوقي,الديوان الرئيسي,ء,الخفيف,ها سَماءً قَد أَكبَرَتها السَماءُ,ضَرَبَ البَحرُ ذو العُبابِ حَوالَي,ضَرَبَ البَحرُ ذو العُبابِ حَوالَي ها سَماء...
198188,الحديث,أحمد شوقي,الديوان الرئيسي,ء,الخفيف,ضِ شِباكاً تَمُدُّها الدَأماءُ,وَرَأى المارِقونَ مِن شَرَكِ الأَر,وَرَأى المارِقونَ مِن شَرَكِ الأَر ضِ شِباك...
198189,الحديث,أحمد شوقي,الديوان الرئيسي,ء,الخفيف,تَتَدَجّى كَأَنَّها الظَلماءُ,وَجِبالاً مَوائِجاً في جِبالٍ,وَجِبالاً مَوائِجاً في جِبالٍ تَتَدَجّى كَأ...
198190,الحديث,أحمد شوقي,الديوان الرئيسي,ء,الخفيف,لُ وَهاجَت حُماتَها الهَيجاءُ,وَدَوِيّاً كَما تَأَهَّبَتِ الخَي,وَدَوِيّاً كَما تَأَهَّبَتِ الخَي لُ وَهاجَ...
...,...,...,...,...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,وأحلى قصيدة تَتَغنى,هي أغلى ما أنشأ اللَّه في الدنيا,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,كحلم يغشى الجفون الوسنى,هي أغرودة الأغاريد تنساب,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يتداعى وجداً ويخفق حسنا,هي شلال بهجة وبهاء,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يدك الحدود سجناً فسجنا,هي حلم الهوى ومنطلقي الباقي,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,آه لو أدرك الغرام لجنا,هي حبي العاتي وكل غرامي,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

In [101]:
df4.duplicated().sum()
df4.drop_duplicates(inplace=True)

/var/folders/c2/f9lh6rmd4q1648_pfl1636zw0000gn/T/ipykernel_47823/1359622779.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop_duplicates(inplace=True)

In [102]:
print(df4.columns)
df4.drop(['القافية', 'البحر', 'الشطر الايسر','الشطر الايمن'],inplace=True,axis=1)

Index(['العصر', 'الشاعر', 'الديوان', 'القافية', 'البحر', 'الشطر الايسر',
       'الشطر الايمن', 'البيت'],
      dtype='object')

/var/folders/c2/f9lh6rmd4q1648_pfl1636zw0000gn/T/ipykernel_47823/4084979309.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop(['القافية', 'البحر', 'الشطر الايسر','الشطر الايمن'],inplace=True,axis=1)

In [103]:
df4

,العصر,الشاعر,الديوان,البيت
198186,الحديث,أحمد شوقي,الديوان الرئيسي,هَمَّتِ الفُلكُ وَاِحتَواها الماءُ وَحَداها...
198187,الحديث,أحمد شوقي,الديوان الرئيسي,ضَرَبَ البَحرُ ذو العُبابِ حَوالَي ها سَماء...
198188,الحديث,أحمد شوقي,الديوان الرئيسي,وَرَأى المارِقونَ مِن شَرَكِ الأَر ضِ شِباك...
198189,الحديث,أحمد شوقي,الديوان الرئيسي,وَجِبالاً مَوائِجاً في جِبالٍ تَتَدَجّى كَأ...
198190,الحديث,أحمد شوقي,الديوان الرئيسي,وَدَوِيّاً كَما تَأَهَّبَتِ الخَي لُ وَهاجَ...
...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

### Fifth source

In [104]:
df5=pd.read_csv("datasets/archive (3)/Arabic_PCD/Arabic Poem Comprehensive Dataset (APCD).csv")
df5

,العصر,الشاعر,الديوان,القافية,البحر,الشطر الايسر,الشطر الايمن,البيت
0,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَأَن تَجمَعا شَملي وَتَنتَظِرا غَدا,خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا,خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا وَأَن...
1,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَلا سُرعَتي يَوماً بِسابِقَةِ الرَدى,فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ,فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ وَلا سُ...
2,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَتَستَوجِبا مَنّاً عَلَيَّ وَتُحمَدا,وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً,وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً وَتَ...
3,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,تُؤامِرُني سِرّاً لِأَصرِمَ مَرثَدا,لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ,لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ تُؤامِرُ...
4,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,د,الطويل,وَأَفرَعَ في لَومي مِراراً وَأَصعَدا,وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ,وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ وَأَفر...
...,...,...,...,...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,وأحلى قصيدة تَتَغنى,هي أغلى ما أنشأ اللَّه في الدنيا,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,كحلم يغشى الجفون الوسنى,هي أغرودة الأغاريد تنساب,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يتداعى وجداً ويخفق حسنا,هي شلال بهجة وبهاء,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,يدك الحدود سجناً فسجنا,هي حلم الهوى ومنطلقي الباقي,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,ن,الخفيف,آه لو أدرك الغرام لجنا,هي حبي العاتي وكل غرامي,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

In [105]:
df5.duplicated().sum()
df5.drop_duplicates(inplace=True)

In [106]:
print(df5.columns)
df5.drop(['القافية', 'البحر', 'الشطر الايسر','الشطر الايمن'],inplace=True,axis=1)

Index(['العصر', 'الشاعر', 'الديوان', 'القافية', 'البحر', 'الشطر الايسر',
       'الشطر الايمن', 'البيت'],
      dtype='object')

In [107]:
df5

,العصر,الشاعر,الديوان,البيت
0,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا وَأَن...
1,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ وَلا سُ...
2,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً وَتَ...
3,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ تُؤامِرُ...
4,قبل الإسلام,عمرو بنِ قُمَيئَة,الديوان الرئيسي,وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ وَأَفر...
...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

In [108]:
df5=df5[df5['العصر']=='الحديث']

In [109]:
df5

,العصر,الشاعر,الديوان,البيت
198186,الحديث,أحمد شوقي,الديوان الرئيسي,هَمَّتِ الفُلكُ وَاِحتَواها الماءُ وَحَداها...
198187,الحديث,أحمد شوقي,الديوان الرئيسي,ضَرَبَ البَحرُ ذو العُبابِ حَوالَي ها سَماء...
198188,الحديث,أحمد شوقي,الديوان الرئيسي,وَرَأى المارِقونَ مِن شَرَكِ الأَر ضِ شِباك...
198189,الحديث,أحمد شوقي,الديوان الرئيسي,وَجِبالاً مَوائِجاً في جِبالٍ تَتَدَجّى كَأ...
198190,الحديث,أحمد شوقي,الديوان الرئيسي,وَدَوِيّاً كَما تَأَهَّبَتِ الخَي لُ وَهاجَ...
...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

## Concatinating sources

In [110]:
df1

,poem_style,poem_text,poem_title,poet_name
2133,عامي,الا واشيب عيني يوم قالوا لي فمان اله وتحقت ان...,ألا واشيب عيني,عبدالله الفيصل
3693,عامي,يا ابناء الارض انتشروا دقت اجراس الميلاد ضموا...,يا أبناء الأرض,طلعت سقيرق
3694,عامي,فرسانا زين الشباب زين الشباب فرسانا نادي الوط...,تسلم إيديكو,طلعت سقيرق
3695,عامي,ارضي يا احلي من الهوي ومن لهفتو سكر المطر لما...,موال: أرضي يا أحلى من الهوى,طلعت سقيرق
3696,عامي,فجرك طلع واله مع زهرك بلادي سيفك حجر واله وما...,الفجر الفلسطيني,طلعت سقيرق
...,...,...,...,...
45336,عامي,انا كخصرك نحيل والدمع راحي تخمينك اني عليل دا...,أَنا كَخصرك نَحيل,عائشة التيمورية
45424,عامي,بتهجر ليه اسير حبك يا روحي ولك اوصاف ترد الرو...,بتهجر ليه أَسير حُبِّك يا روحي,عائشة التيمورية
45426,عامي,انا ما اسلي غرام لو سلوني وروحي في راحات حبك ...,اَنا ما أَسلى غَرام لَو سَلوني,عائشة التيمورية
45484,عامي,سلامة مهجتي م الاه تعا يا قلب نعيها لهو انت ا...,سَلامة مهجَتي م الآه,عائشة التيمورية
50413,عامي,"قالها في اخر حبيبة وهي نفسها التي غني لها ""يام...",الأحلام الكبار,عبدالله عبدالوهاب نعمان

In [119]:
df4

,العصر,الشاعر,الديوان,البيت
198186,الحديث,أحمد شوقي,الديوان الرئيسي,هَمَّتِ الفُلكُ وَاِحتَواها الماءُ وَحَداها...
198187,الحديث,أحمد شوقي,الديوان الرئيسي,ضَرَبَ البَحرُ ذو العُبابِ حَوالَي ها سَماء...
198188,الحديث,أحمد شوقي,الديوان الرئيسي,وَرَأى المارِقونَ مِن شَرَكِ الأَر ضِ شِباك...
198189,الحديث,أحمد شوقي,الديوان الرئيسي,وَجِبالاً مَوائِجاً في جِبالٍ تَتَدَجّى كَأ...
198190,الحديث,أحمد شوقي,الديوان الرئيسي,وَدَوِيّاً كَما تَأَهَّبَتِ الخَي لُ وَهاجَ...
...,...,...,...,...
1831765,الحديث,شهاب غانم,شهاب غانم,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...
1831766,الحديث,شهاب غانم,شهاب غانم,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...
1831767,الحديث,شهاب غانم,شهاب غانم,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا
1831768,الحديث,شهاب غانم,شهاب غانم,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...
1831769,الحديث,شهاب غانم,شهاب غانم,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا

In [113]:
# Check column names to spot the differences
print("DF1 Columns:", df1.columns)
print("DF4 Columns:", df4.columns)

df1.rename(columns={
    'poem_text': 'البيت',      # Example: Change 'poem_text' to 'البيت'
    'poet_name': 'الشاعر',    # Example: Change 'poet_name' to 'الشاعر'
    'poem_style': 'العصر'            # Example: Change 'era' to 'العصر'
}, inplace=True)

DF1 Columns: Index(['poem_style', 'poem_text', 'poem_title', 'poet_name'], dtype='object')
DF4 Columns: Index(['العصر', 'الشاعر', 'الديوان', 'البيت'], dtype='object')

/var/folders/c2/f9lh6rmd4q1648_pfl1636zw0000gn/T/ipykernel_47823/2743885260.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={

In [114]:

df = pd.concat([df1, df4], ignore_index=True)

In [115]:
df

,العصر,البيت,poem_title,الشاعر,الديوان
0,عامي,الا واشيب عيني يوم قالوا لي فمان اله وتحقت ان...,ألا واشيب عيني,عبدالله الفيصل,NaN
1,عامي,يا ابناء الارض انتشروا دقت اجراس الميلاد ضموا...,يا أبناء الأرض,طلعت سقيرق,NaN
2,عامي,فرسانا زين الشباب زين الشباب فرسانا نادي الوط...,تسلم إيديكو,طلعت سقيرق,NaN
3,عامي,ارضي يا احلي من الهوي ومن لهفتو سكر المطر لما...,موال: أرضي يا أحلى من الهوى,طلعت سقيرق,NaN
4,عامي,فجرك طلع واله مع زهرك بلادي سيفك حجر واله وما...,الفجر الفلسطيني,طلعت سقيرق,NaN
...,...,...,...,...,...
778075,الحديث,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...,NaN,شهاب غانم,شهاب غانم
778076,الحديث,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...,NaN,شهاب غانم,شهاب غانم
778077,الحديث,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا,NaN,شهاب غانم,شهاب غانم
778078,الحديث,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...,NaN,شهاب غانم,شهاب غانم
778079,الحديث,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا,NaN,شهاب غانم,شهاب غانم

In [116]:
df.isna().sum()

العصر              0
البيت              0
poem_title    777986
الشاعر             0
الديوان           94
dtype: int64

In [117]:
df.drop("الديوان",axis=1,inplace=True)

In [121]:
df

,العصر,البيت,poem_title,الشاعر
0,عامي,الا واشيب عيني يوم قالوا لي فمان اله وتحقت ان...,ألا واشيب عيني,عبدالله الفيصل
1,عامي,يا ابناء الارض انتشروا دقت اجراس الميلاد ضموا...,يا أبناء الأرض,طلعت سقيرق
2,عامي,فرسانا زين الشباب زين الشباب فرسانا نادي الوط...,تسلم إيديكو,طلعت سقيرق
3,عامي,ارضي يا احلي من الهوي ومن لهفتو سكر المطر لما...,موال: أرضي يا أحلى من الهوى,طلعت سقيرق
4,عامي,فجرك طلع واله مع زهرك بلادي سيفك حجر واله وما...,الفجر الفلسطيني,طلعت سقيرق
...,...,...,...,...
778075,الحديث,هي أغلى ما أنشأ اللَّه في الدنيا وأحلى قصيد...,NaN,شهاب غانم
778076,الحديث,هي أغرودة الأغاريد تنساب كحلم يغشى الجفون ا...,NaN,شهاب غانم
778077,الحديث,هي شلال بهجة وبهاء يتداعى وجداً ويخفق حسنا,NaN,شهاب غانم
778078,الحديث,هي حلم الهوى ومنطلقي الباقي يدك الحدود سجنا...,NaN,شهاب غانم
778079,الحديث,هي حبي العاتي وكل غرامي آه لو أدرك الغرام لجنا,NaN,شهاب غانم

In [122]:
# Find poems ('البيت') that appear more than once
conflicts = df[df.duplicated(subset=['البيت'], keep=False)]

# Sort them so the conflicting rows appear next to each other
conflicts = conflicts.sort_values(by='البيت')

In [127]:
conflicts.head(50)

,العصر,البيت,poem_title,الشاعر
777625,الحديث,,NaN,سليمان العيسى
577652,الحديث,,NaN,محمد إمام العبد
120765,الحديث,,NaN,خليل مطران
750991,الحديث,,NaN,الأخطل الصغير
751718,الحديث,,NaN,نزار قباني
753161,الحديث,,NaN,الهادي آدم
755441,الحديث,,NaN,عمر أبو ريشة
756946,الحديث,,NaN,سليمان العيسى
757000,الحديث,,NaN,سليمان العيسى
757255,الحديث,,NaN,محمد مهدي الجواهري
757637,الحديث,,NaN,ادونيس
757679,الحديث,,NaN,ادونيس
755040,الحديث,,NaN,محمود غنيم
757824,الحديث,,NaN,سعاد الصباح
769955,الحديث,,NaN,نعيم إبراهيم عيسى
758804,الحديث,,NaN,نازك الملائكة
758711,الحديث,,NaN,نازك الملائكة
758636,الحديث,,NaN,نازك الملائكة
757803,الحديث,,NaN,سعاد الصباح
758549,الحديث,,NaN,نازك الملائكة
223359,الحديث,,NaN,إبراهيم المنذر
757956,الحديث,,NaN,سعاد الصباح
758521,الحديث,,NaN,نازك الملائكة
3617,الحديث,,NaN,أحمد شوقي
757874,الحديث,,NaN,سعاد الصباح
757927,الحديث,,NaN,سعاد الصباح
752217,الحديث,آه على بلدي عراقي أثمر الدم في الحقول,NaN,بدر شاكر السياب
751837,الحديث,آه على بلدي عراقي أثمر الدم في الحقول,NaN,محمود درويش
752249,الحديث,أبصرت فيه شخصك في الثياب,NaN,بدر شاكر السياب
751869,الحديث,أبصرت فيه شخصك في الثياب,NaN,محمود درويش
476739,الحديث,أبلغ سلامي مرتضى الجد من حل في دائرة المجد,NaN,محمد رضا الخزاعي
661998,الحديث,أبلغ سلامي مرتضى الجد من حل في دائرة المجد,NaN,محمد رضا الخزاعي
751870,الحديث,أبني كان أبوك نبعا من لهيب من حديد,NaN,محمود درويش
752250,الحديث,أبني كان أبوك نبعا من لهيب من حديد,NaN,بدر شاكر السياب
362610,الحديث,أتراني بعد اعترافي وصدقي أن أذوق العذاب حاش...,NaN,ابن كمونة
444472,الحديث,أتراني بعد اعترافي وصدقي أن أذوق العذاب حاش...,NaN,عدنان الغريفي
452265,الحديث,أتقاضى ما فاتني من سرور في مسائي بوصله وصباحي,NaN,صالح القزويني البغدادي
691686,الحديث,أتقاضى ما فاتني من سرور في مسائي بوصله وصباحي,NaN,أحمد القزويني
752319,الحديث,أتى الغيث و انحلّ عقد السحاب,NaN,بدر شاكر السياب
751939,الحديث,أتى الغيث و انحلّ عقد السحاب,NaN,محمود درويش
691900,الحديث,أحرقت خاله بنار فؤادي وجنتاه فاخضل بالاحراق,NaN,أحمد القزويني
452666,الحديث,أحرقت خاله بنار فؤادي وجنتاه فاخضل بالاحراق,NaN,صالح القزويني البغدادي
751925,الحديث,أحسّ بأني عبرت المدى,NaN,محمود درويش
752305,الحديث,أحسّ بأني عبرت المدى,NaN,بدر شاكر السياب
755677,الحديث,أحن إليكم في الأصائل والضحى,NaN,صقر بن سلطان القاسمي
755537,الحديث,أحن إليكم في الأصائل والضحى,NaN,ز5 أحمد فتحي
752191,الحديث,أختاه لذّ على الهوى ألمي فاستمتعي بهواك وابتسم...,NaN,بدر شاكر السياب
751811,الحديث,أختاه لذّ على الهوى ألمي فاستمتعي بهواك وابتسم...,NaN,محمود درويش
751848,الحديث,أرأيت أرملة الشهيد,NaN,محمود درويش
752228,الحديث,أرأيت أرملة الشهيد,NaN,بدر شاكر السياب

In [125]:
print(f"Number of conflicting entries found: {len(conflicts)}")
display(conflicts[['الشاعر', 'البيت']].head(10))

Number of conflicting entries found: 1609

                    الشاعر البيت
777625       سليمان العيسى
577652     محمد إمام العبد
120765          خليل مطران
750991       الأخطل الصغير
751718          نزار قباني
753161          الهادي آدم
755441       عمر أبو ريشة
756946       سليمان العيسى
757000       سليمان العيسى
757255  محمد مهدي الجواهري

In [ ]:

df.drop_duplicates(subset=['البيت'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"Final number of unique poems: {len(df)}")

Final number of unique poems: 777259

In [ ]:

df.drop("poem_title",axis=1,inplace=True)

In [131]:
df.to_csv("poetry_generation_dataset.csv")